-- ReachAI Context Memory Candidate (Phase-3)
-- Controlled write-back buffer before context_item approval.
-- Idempotent for existing dev/test databases.

CREATE TABLE IF NOT EXISTS `context_memory_candidate` (
    `id`                BIGINT        NOT NULL AUTO_INCREMENT,
    `candidate_key`     VARCHAR(128)  NOT NULL,
    `tenant_id`         VARCHAR(96)   NOT NULL,
    `project_id`        BIGINT        DEFAULT NULL,
    `project_code`      VARCHAR(96)   DEFAULT NULL,
    `namespace_id`      BIGINT        DEFAULT NULL,
    `namespace_key`     VARCHAR(128)  DEFAULT NULL,
    `memory_lane`       VARCHAR(32)   NOT NULL DEFAULT 'RUNTIME_USER',
    `candidate_type`    VARCHAR(32)   NOT NULL COMMENT 'PREFERENCE/FACT/RULE/PAGE_CONTEXT/WORKFLOW_CONTEXT/API_CONTEXT/NOTE',
    `title`             VARCHAR(256)  DEFAULT NULL,
    `content`           MEDIUMTEXT    NOT NULL,
    `summary`           TEXT          DEFAULT NULL,
    `reason`            VARCHAR(512)  DEFAULT NULL,
    `source_type`       VARCHAR(48)   NOT NULL COMMENT 'USER_MESSAGE/USER_CONFIRMED/AGENT_OUTPUT/TRACE/PAGE/WORKFLOW/MANUAL/SYSTEM',
    `source_ref`        VARCHAR(512)  DEFAULT NULL,
    `trace_id`          VARCHAR(128)  DEFAULT NULL,
    `session_id`        VARCHAR(128)  DEFAULT NULL,
    `user_id`           VARCHAR(128)  DEFAULT NULL,
    `external_user_id`  VARCHAR(128)  DEFAULT NULL,
    `global_user_id`    VARCHAR(128)  DEFAULT NULL,
    `agent_id`          VARCHAR(128)  DEFAULT NULL,
    `agent_key`         VARCHAR(128)  DEFAULT NULL,
    `workflow_id`       VARCHAR(128)  DEFAULT NULL,
    `workflow_key`      VARCHAR(128)  DEFAULT NULL,
    `page_instance_id`  VARCHAR(128)  DEFAULT NULL,
    `origin`            VARCHAR(512)  DEFAULT NULL,
    `confidence`        DECIMAL(5,4)  NOT NULL DEFAULT 0.7000,
    `trust_level`       VARCHAR(24)   NOT NULL DEFAULT 'LOW',
    `visibility`        VARCHAR(32)   NOT NULL DEFAULT 'PRIVATE',
    `status`            VARCHAR(24)   NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/APPROVED/REJECTED/EXPIRED/DELETED',
    `proposed_by`       VARCHAR(128)  DEFAULT NULL,
    `reviewed_by`       VARCHAR(128)  DEFAULT NULL,
    `reviewed_at`       DATETIME      DEFAULT NULL,
    `review_reason`     VARCHAR(512)  DEFAULT NULL,
    `approved_item_id`  BIGINT        DEFAULT NULL COMMENT '批准后写入 context_item.id',
    `metadata_json`     MEDIUMTEXT    DEFAULT NULL,
    `expires_at`        DATETIME      DEFAULT NULL,
    `created_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at`        DATETIME      DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_context_memory_candidate_key` (`candidate_key`),
    KEY `idx_context_memory_candidate_scope` (`tenant_id`, `project_code`, `memory_lane`, `status`),
    KEY `idx_context_memory_candidate_user` (`tenant_id`, `user_id`, `status`, `created_at`),
    KEY `idx_context_memory_candidate_session` (`session_id`, `status`, `created_at`),
    KEY `idx_context_memory_candidate_trace` (`trace_id`),
    KEY `idx_context_memory_candidate_agent` (`agent_id`, `status`, `created_at`),
    KEY `idx_context_memory_candidate_review` (`status`, `expires_at`, `created_at`),
    KEY `idx_context_memory_candidate_namespace` (`namespace_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Runtime User Memory 写回候选（确认前缓冲）';
